"""Views, one for each Insta485 page."""
from insta485.views.index import show_index
from insta485.views.index import uploaded_file
from insta485.views.explore import show_explore
from insta485.views.users import show_user
from insta485.views.users import show_followers
from insta485.views.users import show_following
from insta485.views.users import manage_following
from insta485.views.posts import show_post
from insta485.views.posts import handle_post
from insta485.views.posts import handle_like
from insta485.views.posts import handle_comment
from insta485.views.accounts import show_login
from insta485.views.accounts import show_account_create
from insta485.views.accounts import show_account_delete
from insta485.views.accounts import show_account_edit
from insta485.views.accounts import show_update_password
from insta485.views.accounts import auth
from insta485.views.accounts import handle_logout
from insta485.views.accounts import handle_account
